#ifndef __BACKPORT_LINUX_BCMA_DRIVER_CC_H_
#define __BACKPORT_LINUX_BCMA_DRIVER_CC_H_
#include_next <linux/bcma/bcma_driver_chipcommon.h>

#ifndef BCMA_CC_PMU_CHIPCTL_ADDR
#define BCMA_CC_PMU_CHIPCTL_ADDR	0x0650
#define BCMA_CC_PMU_CHIPCTL_DATA	0x0654
#define BCMA_CC_PMU_REGCTL_ADDR		0x0658
#define BCMA_CC_PMU_REGCTL_DATA		0x065C
#define BCMA_CC_PMU_PLLCTL_ADDR		0x0660
#define BCMA_CC_PMU_PLLCTL_DATA		0x0664
#endif

#ifndef BCMA_CC_CAP_EXT_AOB_PRESENT
#define  BCMA_CC_CAP_EXT_SECI_PRESENT  0x00000001
#define  BCMA_CC_CAP_EXT_GSIO_PRESENT  0x00000002
#define  BCMA_CC_CAP_EXT_GCI_PRESENT   0x00000004
#define  BCMA_CC_CAP_EXT_SECI_PUART_PRESENT            0x00000008    /* UART present */
#define  BCMA_CC_CAP_EXT_AOB_PRESENT   0x00000040
#endif


#endif /* __BACKPORT_LINUX_BCMA_DRIVER_CC_H_ */
